nameApp: airports-api
namespace: default
port: 8080
portName: client
    
secret:
  nameSecret: sa-airports-api
  url: jdbc:postgresql://postgres:5432/db_airports
  username: postgres
  password: postgres
  keyUrl: url
  keyUsername: username
  keyPassword: password

secretSiemens:
  name: regsiemens
  configJson: eyJhdXRocyI6eyJjci5zaWVtZW5zLmNvbSI6eyJ1c2VybmFtZSI6ImNyLnNpZW1lbnMuY29tIiwicGFzc3dvcmQiOiJDU0MtVlczNmF6RUo5SjMtOVZlVzd6Ni0iLCJlbWFpbCI6ImRhbi5pYWNvYi5leHRAc2llbWVucy5jb20iLCJhdXRoIjoiWTNJdWMybGxiV1Z1Y3k1amIyMDZRMU5ETFZaWE16Wmhla1ZLT1VvekxUbFdaVmMzZWpZdCJ9fX0=

deployment:
  image: cr.siemens.com/proiect/kafkaairportsapi
  livenessPath: /actuator/health/liveness
  readinessPath: /actuator/health/readiness
  env:
    springUrl: SPRING_DATASOURCE_URL
    springUsername: SPRING_DATASOURCE_USERNAME
    springPassword: SPRING_DATASOURCE_PASSWORD
