apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.nameSecret}}
  namespace: {{ .Values.namespace}}
type: kubernetes.io/basic-auth
stringData:
  url: {{ .Values.secret.url}}
  username: {{ .Values.secret.username}}
  password: {{ .Values.secret.password}}

---

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secretSiemens.name}}
  namespace: {{ .Values.namespace}}
data:
  .dockerconfigjson: {{ .Values.secretSiemens.configJson}}
type: kubernetes.io/dockerconfigjson