apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.nameApp}}
  namespace: {{ .Values.namespace}}
  labels:
    app: {{ .Values.nameApp}}
spec:
  ports:
    - name: {{ .Values.portName}}
      port: {{ .Values.port}}
      targetPort: {{ .Values.port}}
  selector:
    app: {{ .Values.nameApp}}